<a href="https://colab.research.google.com/github/dfrafelipe30/ArbolDeBusquedaBinaria/blob/master/PrimerScript.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np
import pandas as pd

#Trabajando con Tensores


In [0]:
torch.__version__

'1.3.1'

In [0]:
tensor_a = torch.ones(2,2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [0]:
tensor_b = torch.Tensor(2,2)
print(tensor_b)
tensor_b.uniform_(0,1)

tensor([[8.8592e-36, 0.0000e+00],
        [3.7835e-44, 0.0000e+00]])


tensor([[0.5057, 0.3265],
        [0.5155, 0.5302]])

In [0]:
points = torch.tensor([[1.0,2.0],[3.0,4.0]])
print(points)
points[0][1] = 2.5
print(points)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1.0000, 2.5000],
        [3.0000, 4.0000]])


In [0]:
tensor_x = torch.tensor([1,2,3,4])
tensor_x
#torch.unsqueeze(tensor_x,0)
torch.unsqueeze(tensor_x,1)

tensor([[1],
        [2],
        [3],
        [4]])

In [0]:
numpyArray = np.random.randn(2,2)

from_numpy = torch.from_numpy(numpyArray)

#Representar datos con tensores

---



In [0]:
print(from_numpy)
print(torch.mean(from_numpy))
print(torch.mean(from_numpy,dim=0))
print(torch.mean(from_numpy,dim=1))


tensor([[-0.4248,  0.8769],
        [-0.1544, -0.8570]], dtype=torch.float64)
tensor(-0.1398, dtype=torch.float64)
tensor([-0.2896,  0.0099], dtype=torch.float64)
tensor([ 0.2261, -0.5057], dtype=torch.float64)


In [0]:
torch.std(from_numpy,dim = 1)

tensor([0.9204, 0.4968], dtype=torch.float64)

In [0]:
torch.save(from_numpy,'tensor.t')

In [0]:
load = torch.load('tensor.t')

In [0]:
url = "https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv"
dataframe = pd.read_csv(url)
dataframe

Unnamed: 0      ID  ... GKReflexes  Release Clause
0               0  158023  ...        8.0         €226.5M
1               1   20801  ...       11.0         €127.1M
2               2  190871  ...       11.0         €228.1M
3               3  193080  ...       94.0         €138.6M
4               4  192985  ...       13.0         €196.4M
...           ...     ...  ...        ...             ...
18202       18202  238813  ...        9.0           €143K
18203       18203  243165  ...       12.0           €113K
18204       18204  241638  ...       13.0           €165K
18205       18205  246268  ...        9.0           €143K
18206       18206  246269  ...        9.0           €165K

[18207 rows x 89 columns]

In [0]:
dataframe.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [0]:
subset = dataframe[['Overall','Age','International Reputation', 'Weak Foot',
       'Skill Moves']].dropna(axis = 0,how = 'any')
columns = subset.columns[1:]
players = torch.tensor(subset.values).float()
players.shape,players.type()


(torch.Size([18159, 5]), 'torch.FloatTensor')

In [0]:
data = players[:,1:]
data,data.shape

(tensor([[31.,  5.,  4.,  4.],
         [33.,  5.,  4.,  5.],
         [26.,  5.,  5.,  5.],
         ...,
         [16.,  1.,  3.,  2.],
         [17.,  1.,  3.,  2.],
         [16.,  1.,  3.,  2.]]), torch.Size([18159, 4]))

In [0]:
target = players[:,0]
target, target.shape

(tensor([94., 94., 92.,  ..., 47., 47., 46.]), torch.Size([18159]))

In [0]:
mean = torch.mean(data,dim = 0)
print(mean)
std = torch.std(data,dim = 0)
print(std)

tensor([25.1225,  1.1132,  2.9473,  2.3613])
tensor([4.6706, 0.3940, 0.6605, 0.7562])


In [0]:
norm = (data - mean)/torch.sqrt(std)
norm

tensor([[ 2.7196,  6.1919,  1.2953,  1.8845],
        [ 3.6450,  6.1919,  1.2953,  3.0345],
        [ 0.4060,  6.1919,  2.5258,  3.0345],
        ...,
        [-4.2211, -0.1804,  0.0648, -0.4155],
        [-3.7584, -0.1804,  0.0648, -0.4155],
        [-4.2211, -0.1804,  0.0648, -0.4155]])

In [0]:
good = data[torch.ge(target,85)]
average = data[torch.gt(target,70) & torch.lt(target,85)]
notSoGood = data[torch.le(target,70)]

goodMean = torch.mean(good, dim = 0)
averageMean = torch.mean(average, dim = 0)
notSoGoodMean = torch.mean(notSoGood, dim = 0)

#goodMean,averageMean,notSoGoodMean

for i,args in enumerate(zip(columns,goodMean,averageMean,notSoGoodMean)):
  print('{:25}{:6.2f}{:6.2f}{:6.2f}'.format(*args))

Age                       28.35 27.23 24.37
International Reputation   3.38  1.36  1.01
Weak Foot                  3.45  3.11  2.89
Skill Moves                3.04  2.75  2.22
